// src/navConfig.js
import { lazy } from "react";

// Lazy load all page components for code splitting and faster initial load
const LandingPage = lazy(() => import("./pages/LandingPage"));
const SevenDayCostForecaster = lazy(() =>
  import("./pages/SevenDayCostForecaster")
);
const HeatPumpEnergyFlow = lazy(() => import("./pages/HeatPumpEnergyFlow"));
const SystemPerformanceAnalyzer = lazy(() =>
  import("./pages/SystemPerformanceAnalyzer")
);
const GasVsHeatPump = lazy(() => import("./pages/GasVsHeatPump"));
const HeatPumpChargingCalc = lazy(() => import("./pages/HeatPumpChargingCalc"));
const CalculationMethodology = lazy(() =>
  import("./pages/CalculationMethodology")
);
const HomeDashboard = lazy(() => import("./pages/Home"));
const HomeHealth = lazy(() => import("./pages/HomeHealth"));
const SettingsPage = lazy(() => import("./pages/Settings"));
const ThermostatStrategyAnalyzer = lazy(() =>
  import("./pages/ThermostatStrategyAnalyzer")
);
const MonthlyBudgetPlanner = lazy(() => import("./pages/MonthlyBudgetPlanner"));
const ProfessionalMode = lazy(() => import("./pages/ProfessionalMode"));
const Onboarding = lazy(() => import("./pages/Onboarding"));
const Tools = lazy(() => import("./pages/Tools"));
const EnergyPlusLoadCalc = lazy(() => import("./pages/EnergyPlusLoadCalc"));
const WiringDiagramGenerator = lazy(() => import("./pages/WiringDiagramGenerator"));
const EquipmentSettingsGuide = lazy(() => import("./pages/EquipmentSettingsGuide"));
const HVACTroubleshooting = lazy(() => import("./pages/HVACTroubleshooting"));
const AskJouleHelp = lazy(() => import("./pages/AskJouleHelp"));
const ContactorDemo = lazy(() => import("./pages/ContactorDemo"));
const SmartThermostatDemo = lazy(() => import("./pages/SmartThermostatDemo"));
const AirQualityHMI = lazy(() => import("./pages/AirQualityHMI"));
const AgentConsole = lazy(() => import("./pages/AgentConsole"));
const UpgradeROIAnalyzer = lazy(() => import("./pages/UpgradeROIAnalyzer"));
const AskJouleCommandCenter = lazy(() =>
  import("./pages/AskJouleCommandCenter")
);
const HeatPumpGuide = lazy(() => import("./pages/HeatPumpGuide"));
const ThermostatDiagrams = lazy(() => import("./pages/ThermostatDiagrams"));
const SmartThermostatBuildGuide = lazy(() =>
  import("./pages/SmartThermostatBuildGuide")
);
const MarkdownPage = lazy(() => import("./pages/MarkdownPage"));
const Upgrades = lazy(() => import("./pages/Upgrades"));
const DocumentationSetupGuides = lazy(() =>
  import("./pages/DocumentationSetupGuides")
);
const EcobeeSettingsSandbox = lazy(() => import("./pages/EcobeeSettingsSandbox"));
const EcobeeTransitionPlanner = lazy(() =>
  import("./pages/EcobeeTransitionPlanner")
);
const EcobeeEquipmentMatrix = lazy(() => import("./pages/EcobeeEquipmentMatrix"));
const EcobeeVentilatorExplainer = lazy(() => import("./pages/EcobeeVentilatorExplainer"));
const EcobeeVentilatorWizard = lazy(() => import("./pages/EcobeeVentilatorWizard"));
const WholeHouseVentilationEcobeeGuide = lazy(() => import("./pages/WholeHouseVentilationEcobeeGuide"));
const EcobeeAuxHeatSimulator = lazy(() => import("./pages/EcobeeAuxHeatSimulator"));
const EcobeeReplayLastNight = lazy(() => import("./pages/EcobeeReplayLastNight"));
const EcobeeFrostControlFix = lazy(() => import("./pages/EcobeeFrostControlFix"));
const TwoWaySwitchExplainer = lazy(() => import("./pages/TwoWaySwitchExplainer"));
const TwoWaySwitchWiringVisualizer = lazy(() => import("./pages/TwoWaySwitchWiringVisualizer"));
const KnowledgeBaseSearch = lazy(() => import("./pages/KnowledgeBaseSearch"));
const ComfortSettingStrangenessFix = lazy(() => import("./pages/ComfortSettingStrangenessFix"));
const HVACStaticPressure = lazy(() => import("./pages/HVACStaticPressure"));
const Analysis = lazy(() => import("./pages/Analysis"));
const Control = lazy(() => import("./pages/Control"));
const Hardware = lazy(() => import("./pages/Hardware"));
const Checkout = lazy(() => import("./pages/Checkout"));
const SummerACIssues = lazy(() => import("./pages/SummerACIssues"));
const WeeklyForecast = lazy(() => import("./pages/WeeklyForecast"));
const MonthlyBudget = lazy(() => import("./pages/MonthlyBudget"));
const AudioTranscription = lazy(() => import("./pages/AudioTranscription"));
const IPLookup = lazy(() => import("./pages/IPLookup"));
const PDFToText = lazy(() => import("./pages/PDFToText"));
const ImageToASCII = lazy(() => import("./pages/ImageToASCII"));
const ImageToText = lazy(() => import("./pages/ImageToText"));
const BlueairControl = lazy(() => import("./pages/BlueairControl"));
const OptimizationHub = lazy(() => import("./pages/OptimizationHub"));
const BridgeSupport = lazy(() => import("./pages/BridgeSupport"));
const RemoteSettings = lazy(() => import("./pages/RemoteSettings"));
const SupportTicket = lazy(() => import("./pages/SupportTicket"));
const OfflineLauncher = lazy(() => import("./pages/OfflineLauncher"));

import {
  Home as HomeIcon,
  Calendar,
  TrendingUp,
  Search,
  BarChart2,
  Activity,
  Zap,
  FileText,
  Settings as SettingsIcon,
  Bot,
  Thermometer,
  Box,
  Wind,
  Server,
  ShoppingCart,
  Heart,
  Bug,
  Calculator,
  Cable,
  Wrench,
  Wrench as Tool,
  FileAudio,
  Network,
  Image,
  Sparkles,
  MessageSquare,
  Chrome,
  MapPin,
  DollarSign,
  Moon,
  Gauge,
} from "lucide-react";

export const routes = [
  // Landing page removed for Reddit demo - app opens directly to onboarding
  // {
  //   path: "/",
  //   name: "Landing",
  //   label: "Home",
  //   icon: HomeIcon,
  //   Component: LandingPage,
  //   exact: true,
  //   showInNav: false,
  //   inMobileNav: false,
  //   inPrimaryNav: false,
  //   description: "Joule Landing Page",
  // },
  // ===== THE GOLDEN PATH: 5 MAIN TABS =====
  {
    path: "/home-health",
    name: "Home Health",
    label: "Home Health",
    icon: Heart,
    Component: HomeHealth,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description:
      "Simple, friendly heat pump status — no engineering degree required",
  },
  {
    path: "/home",
    name: "Mission Control",
    label: "Mission Control",
    icon: HomeIcon,
    Component: HomeDashboard,
    showInNav: true,
    inMobileNav: true,
    inPrimaryNav: true,
    description: "Energy dashboard & overview",
  },
  {
    path: "/tools/ecobee-transition-planner",
    name: "Ecobee Planner",
    label: "Ecobee Planner",
    icon: Thermometer,
    Component: EcobeeTransitionPlanner,
    showInNav: false,
    inMobileNav: true,
    inPrimaryNav: false,
    description: "Visualize Ecobee schedule transitions to avoid immediate restarts",
  },
  {
    path: "/tools/ecobee-settings-sandbox",
    name: "Ecobee Settings Sandbox",
    label: "Ecobee Settings Sandbox",
    icon: SettingsIcon,
    Component: EcobeeSettingsSandbox,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Virtual playground for Ecobee Premium installation settings and thresholds. See which settings appear/disappear based on equipment configuration.",
  },
  {
    path: "/tools/ecobee-equipment-matrix",
    name: "Ecobee Equipment Matrix",
    label: "Ecobee Equipment Matrix",
    icon: Cable,
    Component: EcobeeEquipmentMatrix,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Equipment configuration matrix with wiring diagrams for Ecobee Premium. Shows common setups, required terminals, and ASCII wiring diagrams.",
  },
  {
    path: "/tools/ecobee-ventilator-explainer",
    name: "Ecobee Ventilator Explainer",
    label: "Ecobee Ventilator Explainer",
    icon: Thermometer,
    Component: EcobeeVentilatorExplainer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Interactive explainer for whole-home ventilator control with Ecobee Premium. Wiring diagrams, relay simulator, and settings navigation.",
  },
  {
    path: "/tools/ecobee-ventilator-wizard",
    name: "Ecobee Ventilator Setup Wizard",
    label: "Ecobee Ventilator Setup Wizard",
    icon: Thermometer,
    Component: EcobeeVentilatorWizard,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Interactive wiring wizard and Ecobee menu simulator for setting up whole-home ventilation control.",
  },  {
    path: "/tools/whole-house-ventilation-ecobee-guide",
    name: "Whole-House Ventilation + Ecobee Visual Guide",
    label: "Whole-House Ventilation + Ecobee Visual Guide",
    icon: Thermometer,
    Component: WholeHouseVentilationEcobeeGuide,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Visual guide with ASCII diagrams showing ventilation system types, 2-story home cutaways, and Ecobee ACC wiring patterns (24VAC vs dry contact).",
  },
  {
    path: "/tools/ecobee-aux-heat-simulator",
    name: "Ecobee Aux Heat Simulator",
    label: "Ecobee Aux Heat Simulator",
    icon: Thermometer,
    Component: EcobeeAuxHeatSimulator,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Interactive simulator for heat pump auxiliary heat decision logic. Shows when aux heat engages based on temperature differentials and system settings.",
  },
  {
    path: "/tools/ecobee-replay-last-night",
    name: "Replay Last Night",
    label: "Replay Last Night: Aux Heat Simulator",
    icon: Zap,
    Component: EcobeeReplayLastNight,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare AUTO vs MANUAL staging to optimize aux heat usage. See why 'Aux starts at 40°F' nukes your bill.",
  },
  {
    path: "/tools/ecobee-frost-control-fix",
    name: "Ecobee Frost Control Fix",
    label: "Ecobee Frost Control Missing?",
    icon: Thermometer,
    Component: EcobeeFrostControlFix,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Fix for Ecobee thermostat frost control settings disappearing. Interactive guide to resolve the AC Overcooling bug.",
  },
  {
    path: "/tools/hvac-static-pressure",
    name: "HVAC Static Pressure",
    label: "HVAC Static Pressure Analyzer",
    icon: Gauge,
    Component: HVACStaticPressure,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Analyze how ductwork static pressure affects furnace performance, efficiency, and blower motor lifespan. Interactive tool to understand pressure impact.",
  },
  {
    path: "/tools/two-way-switch-explainer",
    name: "Two-Way Switch Explainer",
    label: "Two-Way Switch Explainer",
    icon: Cable,
    Component: TwoWaySwitchExplainer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Interactive explainer for 3-way switch wiring, phantom voltage, neutral connections, and NEC code references.",
  },
  {
    path: "/tools/two-way-switch-wiring-visualizer",
    name: "Two-Way Switch Wiring Visualizer",
    label: "Two-Way Switch Wiring Visualizer",
    icon: Cable,
    Component: TwoWaySwitchWiringVisualizer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Animated visualizer showing 3-way switch contacts, traveler voltage states, ASCII diagrams, induction formulas, and NEC references.",
  },
  {
    path: "/tools/knowledge-base-search",
    name: "Knowledge Base Search",
    label: "Search Knowledge Base",
    icon: Search,
    Component: KnowledgeBaseSearch,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Ask questions about Manual J, load calculations, sizing, or HVAC engineering standards. Includes information from user-uploaded PDFs.",
  },
  {
    path: "/tools/comfort-setting-strangeness-fix",
    name: "Comfort Setting Strangeness Fix",
    label: "Comfort Setting Strangeness Fix",
    icon: Moon,
    Component: ComfortSettingStrangenessFix,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Interactive guide explaining why sensor participation changes early in Ecobee schedules, with simulations and fixes.",
  },
  {
    path: "/analysis",
    name: "Simulation",
    label: "Simulation",
    icon: BarChart2,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Forecast, budget, compare, and analyzer",
  },
  {
    path: "/analysis/budget",
    name: "Budget",
    label: "Monthly Forecast",
    icon: TrendingUp,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Monthly budget planning",
  },
  {
    path: "/analysis/compare",
    name: "Heat Pump vs Gas Furnace Cost",
    label: "Heat Pump vs Gas Furnace Cost",
    icon: Search,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Gas vs Heat Pump comparison",
  },
  {
    path: "/control",
    name: "Climate",
    label: "Climate",
    icon: Thermometer,
    Component: Control,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Thermostat and air quality control",
  },
  {
    path: "/control/thermostat",
    name: "Thermostat",
    label: "Thermostat",
    icon: Thermometer,
    Component: Control,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Smart thermostat control",
  },
  {
    path: "/control/air-quality",
    name: "Air Quality",
    label: "Air Quality",
    icon: Wind,
    Component: Control,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Dehumidifier and air purifier control",
  },
  {
    path: "/control/blueair",
    name: "Blueair Control",
    label: "Blueair Control",
    icon: Wind,
    Component: BlueairControl,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Control your Blueair air purifier",
  },
  {
    path: "/summer/ac-issues",
    name: "SummerACIssues",
    label: "AC Troubleshooting",
    icon: Wind,
    Component: SummerACIssues,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description:
      "Summer AC troubleshooting - sticky house, high humidity, short cycling",
  },
  {
    path: "/hardware",
    name: "Docs",
    label: "Docs",
    icon: FileText,
    Component: Hardware,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Documentation and knowledge base",
  },
  {
    path: "/config",
    name: "Settings",
    label: "Settings",
    icon: SettingsIcon,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "App settings",
  },
  // ===== LEGACY ROUTES (Hidden but kept for backward compatibility) =====
  {
    path: "/dashboard",
    name: "Dashboard",
    label: "Dashboard",
    icon: BarChart2,
    Component: HomeDashboard,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Energy dashboard & overview - redirects to /home",
  },
  {
    path: "/app",
    name: "Thermostat",
    label: "Thermostat",
    icon: HomeIcon,
    Component: SmartThermostatDemo,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Smart thermostat control - redirects to /control/thermostat",
  },
  {
    path: "/cost-forecaster",
    name: "Forecast",
    label: "Forecast",
    icon: Calendar,
    Component: SevenDayCostForecaster,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "7-day cost forecast - redirects to /analysis/forecast",
  },
  {
    path: "/monthly-budget",
    name: "Budget",
    label: "Budget",
    icon: TrendingUp,
    Component: MonthlyBudgetPlanner,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Monthly budget planning - redirects to /analysis/budget",
  },
  {
    path: "/air-quality",
    name: "Air Quality",
    label: "Air Quality",
    icon: Wind,
    Component: AirQualityHMI,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description:
      "Dehumidifier and air purifier control - redirects to /control/air-quality",
  },
  {
    path: "/settings",
    name: "Settings",
    label: "Settings",
    icon: SettingsIcon,
    Component: SettingsPage,
    showInNav: true,
    inMobileNav: true,
    inPrimaryNav: true,
    description: "App settings",
  },
  {
    path: "/settings/home-setup",
    name: "Home Setup",
    label: "Home Setup",
    icon: HomeIcon,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Tell Joule about your home so estimates match reality",
  },
  {
    path: "/settings/system-config",
    name: "System Configuration",
    label: "System Configuration",
    icon: Zap,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Describe your HVAC system so Joule can model it accurately",
  },
  {
    path: "/settings/costs-rates",
    name: "Costs & Rates",
    label: "Costs & Rates",
    icon: DollarSign,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Set utility rates and pricing preferences",
  },
  {
    path: "/settings/thermostat",
    name: "Thermostat Preferences",
    label: "Thermostat Preferences",
    icon: Thermometer,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Describe your typical thermostat preferences (for estimates only)",
  },
  {
    path: "/settings/bridge-ai",
    name: "Bridge & AI",
    label: "Bridge & AI",
    icon: Server,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Connect hardware and configure AI features",
  },
  {
    path: "/bridge-support",
    name: "Bridge Diagnostics",
    label: "Bridge Diagnostics",
    icon: Server,
    Component: BridgeSupport,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Self-service diagnostics and troubleshooting. Check status, view logs, and perform basic maintenance tasks.",
  },
  {
    path: "/remote-settings",
    name: "Remote Settings",
    label: "Remote Settings",
    icon: SettingsIcon,
    Component: RemoteSettings,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Configure all user settings remotely via Tailscale. Accessible through Bridge Diagnostics.",
  },
  // ===== HIDDEN/ADVANCED TOOLS (Not in main nav) =====
  {
    path: "/cost-comparison",
    name: "Heat Pump vs Gas Furnace Cost",
    label: "Heat Pump vs Gas Furnace Cost",
    icon: Search,
    Component: GasVsHeatPump,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Gas vs Heat Pump comparison - use /analysis/compare",
  },
  {
    path: "/thermostat-analyzer",
    name: "Thermostat",
    label: "Thermostat",
    icon: Search,
    Component: ThermostatStrategyAnalyzer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Thermostat strategy analysis - hidden",
  },
  {
    path: "/performance-analyzer",
    name: "Analyzer",
    label: "Analyzer",
    icon: BarChart2,
    Component: SystemPerformanceAnalyzer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "System performance analysis - use /analysis/analyzer",
  },
  {
    path: "/energy-flow",
    name: "Flow",
    label: "Flow",
    icon: Activity,
    Component: HeatPumpEnergyFlow,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Energy flow visualization - hidden (too nerdy)",
  },
  {
    path: "/charging-calculator",
    name: "Charge",
    label: "Charge",
    icon: Zap,
    Component: HeatPumpChargingCalc,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "A/C charging calculator - hidden (installer tool)",
  },
  {
    path: "/methodology",
    name: "Method",
    label: "Method",
    icon: FileText,
    Component: CalculationMethodology,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Calculation methodology - hidden",
  },
  {
    path: "/contactor-demo",
    name: "Contactors",
    label: "Contactor Demo",
    icon: Zap,
    Component: ContactorDemo,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Live contactor animation - hidden (dev tool)",
  },
  {
    path: "/ask-joule-help",
    name: "Help",
    label: "Ask Joule Help",
    Component: AskJouleHelp,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Ask Joule user manual and commands",
  },
  {
    path: "/professional",
    name: "Professional",
    label: "Professional",
    Component: ProfessionalMode,
    showInNav: false,
    hideInNav: true,
    inMobileNav: false,
    inPrimaryNav: false,
  },
  // ===== TOOLS SECTION =====
  {
    path: "/tools",
    name: "Tools",
    label: "Tools",
    icon: Tool,
    Component: Tools,
    showInNav: true,
    inMobileNav: true,
    inPrimaryNav: true,
    description: "HVAC calculation, wiring, and troubleshooting tools",
  },
  {
    path: "/tools/energyplus",
    name: "EnergyPlus Load Calc",
    label: "EnergyPlus Load Calculator",
    icon: Calculator,
    Component: EnergyPlusLoadCalc,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "ACCA Manual J-compliant load calcs using DOE EnergyPlus. Get your BTUs, tons, and sizing right the first time. No more guessing on SEER, HSPF, or AFUE ratings.",
  },
  {
    path: "/tools/wiring-diagram",
    name: "Wiring Diagram Generator",
    label: "Wiring Diagram Generator",
    icon: Cable,
    Component: WiringDiagramGenerator,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Generate ASCII wiring diagrams for Ecobee thermostat installs. Handles PEK setups, heat pump configs, conventional systems, and all that jazz. No C-wire? No problem.",
  },
  {
    path: "/tools/equipment-settings",
    name: "Equipment Settings Guide",
    label: "Equipment Settings Guide",
    icon: SettingsIcon,
    Component: EquipmentSettingsGuide,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Answers to equipment compatibility Qs and config guides. Boiler setups, heat pump settings, aux heat thresholds - all the deets you need to dial it in.",
  },
  {
    path: "/tools/hvac-troubleshooting",
    name: "HVAC Troubleshooting",
    label: "HVAC Troubleshooting",
    icon: Wrench,
    Component: HVACTroubleshooting,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Step-by-step troubleshooting guides for common HVAC problems. Short cycling, no heat, frozen coils, pressure switch issues - we got you covered.",
  },
  {
    path: "/tools/heat-pump-vs-gas-furnace",
    name: "Heat Pump vs Gas Furnace Cost",
    label: "Heat Pump vs Gas Furnace Cost",
    icon: Search,
    Component: GasVsHeatPump,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare heat pump vs gas furnace costs for your home and climate.",
  },
  {
    path: "/tools/city-cost-comparison",
    name: "City Cost Comparison",
    label: "City Cost Comparison",
    icon: MapPin,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare heating and cooling costs between different cities and climates",
  },
  {
    path: "/tools/city-cost-comparison/heat-pump",
    name: "Heat Pump City Cost Comparison",
    label: "Heat Pump City Cost Comparison",
    icon: MapPin,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare heating and cooling costs between cities using heat pumps",
  },
  {
    path: "/tools/city-cost-comparison/gas-electric",
    name: "Gas+Electric City Cost Comparison",
    label: "Gas+Electric City Cost Comparison",
    icon: MapPin,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare heating and cooling costs between cities using gas furnace + electric AC",
  },
  {
    path: "/tools/audio-transcription",
    name: "Audio Transcription",
    label: "Audio Transcription",
    icon: FileAudio,
    Component: AudioTranscription,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Upload WAV files and convert them to text using OpenAI Whisper API. Perfect for transcribing phone calls, meetings, or voice notes.",
  },
  {
    path: "/tools/ip-lookup",
    name: "IP Lookup",
    label: "IP Lookup",
    icon: Network,
    Component: IPLookup,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Reverse IP address lookup tool. Get location, ISP, timezone, and network information for any IP address.",
  },
  {
    path: "/tools/pdf-to-text",
    name: "PDF to Text",
    label: "PDF to Text",
    icon: FileText,
    Component: PDFToText,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Extract text from PDF files. Works entirely in your browser - no data is sent to any server. Perfect for converting PDFs to text format.",
  },
  {
    path: "/tools/image-to-ascii",
    name: "Image to ASCII",
    label: "Image to ASCII Converter",
    icon: Image,
    Component: ImageToASCII,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Convert images to ASCII art. Perfect for extracting diagrams from manuals and adding them to the RAG database.",
  },
  {
    path: "/tools/image-to-text",
    name: "Image to Text",
    label: "Image to Text (OCR)",
    icon: FileText,
    Component: ImageToText,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Extract text from images and screenshots using OCR. Perfect for extracting text from PDF images or scanned documents.",
  },
  {
    path: "/tools/support-ticket",
    name: "Support Ticket",
    label: "Support Ticket",
    icon: MessageSquare,
    Component: SupportTicket,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Submit a support ticket with diagnostic information for troubleshooting",
  },
  {
    path: "/tools/bridge-support",
    name: "Bridge Diagnostics",
    label: "Bridge Diagnostics",
    icon: Server,
    Component: BridgeSupport,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Self-service diagnostics and troubleshooting. Check status, view logs, and perform basic maintenance tasks.",
  },
  {
    path: "/tools/offline-launcher",
    name: "Offline Launcher",
    label: "Offline Launcher",
    icon: Chrome,
    Component: OfflineLauncher,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Launch the app in Chrome for offline access. Cache the app while online, then use it even when your internet connection is down.",
  },
  {
    path: "/onboarding",
    name: "Onboarding",
    label: "Onboarding",
    Component: Onboarding,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
  },
  {
    path: "/upgrade-roi",
    name: "Upgrades",
    label: "Upgrades",
    icon: TrendingUp,
    Component: UpgradeROIAnalyzer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Upgrade ROI analyzer - hidden",
  },
  {
    path: "/ask-joule-command-center",
    name: "Ask Joule Command Center",
    label: "Ask Joule Command Center",
    icon: FileText,
    Component: AskJouleCommandCenter,
    showInNav: false,
    hideInNav: true,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Command history, export, and review for Ask Joule",
  },
  {
    path: "/heat-pump-guide",
    name: "Heat Pump Guide",
    label: "Heat Pump Guide",
    icon: Thermometer,
    Component: HeatPumpGuide,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Understanding your heat pump - moved to footer/help",
  },
  {
    path: "/documentation-setup-guides",
    name: "Documentation & Setup Guides",
    label: "Docs",
    icon: FileText,
    Component: DocumentationSetupGuides,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Complete guides - moved to /hardware",
  },
  {
    path: "/thermostat-diagrams",
    name: "Drawings",
    label: "Drawings",
    icon: Box,
    Component: ThermostatDiagrams,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Wiring diagrams - moved to footer/help",
  },
  {
    path: "/smart-thermostat-build-guide",
    name: "Smart Thermostat Build Guide",
    label: "Build Guide",
    icon: FileText,
    Component: SmartThermostatBuildGuide,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Build guide - moved to footer/help",
  },
  {
    path: "/docs/:filename",
    name: "Markdown Viewer",
    label: "Documentation",
    Component: MarkdownPage,
    showInNav: false,
    hideInNav: true,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Markdown document viewer",
  },
  {
    path: "/upgrades",
    name: "Upgrades Shop",
    label: "Shop",
    icon: Zap,
    Component: Upgrades,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Joule Monitor & Bridge products - moved to /hardware",
  },
  {
    path: "/checkout",
    name: "Checkout",
    label: "Checkout",
    icon: ShoppingCart,
    Component: Checkout,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Checkout page with sales questions",
  },
  // ===== DEBUG PAGES (Uses Ecobee target temp directly via Joule Bridge) =====
  {
    path: "/analysis/energy-flow",
    name: "Performance",
    label: "Performance",
    icon: Activity,
    Component: HeatPumpEnergyFlow,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Visualize heat pump performance and see when backup heat is needed.",
  },
  {
    path: "/analysis/weekly-forecast",
    name: "Cost Forecaster",
    label: "Weekly Forecast",
    icon: Bug,
    Component: WeeklyForecast,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "7-day forecast using Ecobee target temp directly (no scheduling)",
  },
  {
    path: "/analysis/monthly-budget",
    name: "Monthly Forecast",
    label: "Monthly Forecast",
    icon: Calendar,
    Component: MonthlyBudget,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Current month budget with daily breakdown",
  },
  {
    path: "/analysis/city-comparison",
    name: "City Cost Comparison",
    label: "City Cost Comparison",
    icon: MapPin,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare heating and cooling costs between different cities and climates",
  },
  {
    path: "/analysis/city-comparison/heat-pump",
    name: "Heat Pump City Cost Comparison",
    label: "Heat Pump City Cost Comparison",
    icon: MapPin,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare heating and cooling costs between cities using heat pumps",
  },
  {
    path: "/analysis/city-comparison/gas-electric",
    name: "Gas+Electric City Cost Comparison",
    label: "Gas+Electric City Cost Comparison",
    icon: MapPin,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Compare costs between cities using gas heating and electric cooling",
  },
  {
    path: "/analysis/annual",
    name: "Annual Forecast",
    label: "Annual Forecast",
    icon: TrendingUp,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "View annual heating and cooling cost breakdown",
  },
  {
    path: "/analysis/analyzer",
    name: "Analyze System",
    label: "Analyze System",
    icon: BarChart2,
    Component: SystemPerformanceAnalyzer,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "System performance analysis",
  },
  {
    path: "/analysis/forecast",
    name: "Cost Forecaster",
    label: "Weekly Forecast",
    icon: Calendar,
    Component: Analysis,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "7-day cost forecast",
  },
  {
    path: "/optimize",
    name: "Optimizer",
    label: "Optimizer",
    icon: Sparkles,
    Component: OptimizationHub,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "Smart optimization hub - save money with one-click optimizations",
  },
  {
    path: "/config",
    name: "Settings",
    label: "Settings",
    icon: SettingsIcon,
    Component: SettingsPage,
    showInNav: false,
    inMobileNav: false,
    inPrimaryNav: false,
    description: "App settings",
  },
];

// Synchronize header and mobile nav with the routes array
export const headerNav = routes.filter((r) => r.showInNav && !r.hideInNav);
export const mobileNav = routes.filter(
  (r) => (r.showInNav || r.showInMoreMenu) && !r.hideInNav
);

export default routes;
